- hosts: all
  tasks:

    - name: Install Predependencies
      include: install-dependencies.yaml
      tags:
        - install
        - upgrade-charm

    - name: Run Config-changed
      include: config-changed.yaml
      tags:
        - config-changed

    - name: Run DB Relation Changed
      include: db-relation-changed.yaml
      tags:
        - database-relation-changed


    - debug: msg="start"
      tags:
        - start
